module Recipe exposing
    ( Amount
    , Ingredient
    , IngredientGroup
    , Recipe
    , Rescue
    , Step
    , Yield
    , decoder
    , dominantAcid
    , path
    )

{-| A recipe, as `scripts/recipe.ts` writes it.

**This type mirrors the build's JSON exactly and adds nothing.** The
markdown is the source of record and the build is what validates it,
so a field that is not in `public/content/recipes/<slug>.json` has no
business being invented here — if the page wants it, the schema wants
it, and that is an edit to DS-01 §06 first.

The decoder is deliberately strict. A missing field is a build that
went wrong, not a recipe to render half of: silently defaulting a
`yield` to zero would put a wrong number on a printed sheet, and the
sheet outlives the bug.

-}

import Json.Decode as D exposing (Decoder)



-- THE DOCUMENT


type alias Recipe =
    { slug : String
    , title : String
    , tested : String
    , yield : Yield
    , time : { active : Int, total : Int }
    , slot : List String
    , course : String
    , flavor : List String
    , method : String
    , effort : String
    , dietary : List String
    , cuisine : List String
    , print : String
    , photo : Maybe String
    , ingredients : List IngredientGroup
    , equipment : List String
    , steps : List Step
    , watchpoints : List String
    , rescues : List Rescue
    , keeps : List String
    , note : List String
    }


type alias Yield =
    { amount : Float, unit : String, servings : Maybe Int }


type alias Amount =
    { value : Float, max : Maybe Float, text : String }


type alias Ingredient =
    { amount : Maybe Amount
    , unit : Maybe String
    , unitKind : Maybe String
    , indivisible : Bool
    , item : String
    , note : Maybe String
    }


type alias IngredientGroup =
    { name : Maybe String, items : List Ingredient }


type alias Step =
    { n : Int
    , text : String
    , cue : Maybe String

    -- Seconds, when the cue named a duration. A range carries its LOW
    -- end: the timer says when to start looking, not when to stop.
    , timer : Maybe Int
    }


type alias Rescue =
    { symptom : String, recoverable : Bool, text : String }



-- WHERE IT LIVES


{-| Where a recipe's JSON is fetched from. Generated by the content
build into `public/`, so the path is stable and unhashed — Vite copies
`public/` verbatim.
-}
path : String -> String
path slug =
    "/content/recipes/" ++ slug ++ ".json"



-- THE ONE ACID


{-| The acid a recipe page runs on — DS-01 §04.

**One acid dominates a surface; a second may cameo; never three.** A
recipe takes the acid of its dominant method, so the colour on the
page names a physical state of the food rather than decorating it:
heat for anything that burns you, cold for the chain that must not
break, live for anything alive in the jar.

Returns the token suffix (`heat`, `cold`, `live`, `act`), which the
view turns into a `--page-*` custom property. Marks only — the quiet
layer never fills.

-}
dominantAcid : Recipe -> String
dominantAcid recipe =
    case recipe.method of
        "ferment" ->
            "live"

        "pickle" ->
            "live"

        "cure" ->
            "live"

        "dough" ->
            "live"

        "chill" ->
            "cold"

        "freeze" ->
            "cold"

        "no-cook" ->
            "cold"

        "blend" ->
            "act"

        _ ->
            -- Every remaining method applies heat to something.
            "heat"



-- DECODING


decoder : Decoder Recipe
decoder =
    let
        -- Elm's `map` family stops at 8, and a recipe has 24 fields.
        -- `andThen` chaining would nest 24 deep; this stays flat.
        field name dec =
            D.map2 (|>) (D.field name dec)
    in
    D.succeed Recipe
        |> field "slug" D.string
        |> field "title" D.string
        |> field "tested" D.string
        |> field "yield" yieldDecoder
        |> field "time" timeDecoder
        |> field "slot" (D.list D.string)
        |> field "course" D.string
        |> field "flavor" (D.list D.string)
        |> field "method" D.string
        |> field "effort" D.string
        |> field "dietary" (D.list D.string)
        |> field "cuisine" (D.list D.string)
        |> field "print" D.string
        |> field "photo" (D.nullable D.string)
        |> field "ingredients" (D.list groupDecoder)
        |> field "equipment" (D.list D.string)
        |> field "steps" (D.list stepDecoder)
        |> field "watchpoints" (D.list D.string)
        |> field "rescues" (D.list rescueDecoder)
        |> field "keeps" (D.list D.string)
        |> field "note" (D.list D.string)


yieldDecoder : Decoder Yield
yieldDecoder =
    D.map3 Yield
        (D.field "amount" D.float)
        (D.field "unit" D.string)
        -- absent rather than null: a sauce yields grams, and claiming
        -- it serves anybody is a number nobody measured
        (D.maybe (D.field "servings" D.int))


timeDecoder : Decoder { active : Int, total : Int }
timeDecoder =
    D.map2 (\a t -> { active = a, total = t })
        (D.field "active" D.int)
        (D.field "total" D.int)


groupDecoder : Decoder IngredientGroup
groupDecoder =
    D.map2 IngredientGroup
        (D.field "name" (D.nullable D.string))
        (D.field "items" (D.list ingredientDecoder))


ingredientDecoder : Decoder Ingredient
ingredientDecoder =
    D.map6 Ingredient
        (D.field "amount" (D.nullable amountDecoder))
        (D.field "unit" (D.nullable D.string))
        (D.field "unitKind" (D.nullable D.string))
        (D.field "indivisible" D.bool)
        (D.field "item" D.string)
        (D.field "note" (D.nullable D.string))


amountDecoder : Decoder Amount
amountDecoder =
    D.map3 Amount
        (D.field "value" D.float)
        (D.maybe (D.field "max" D.float))
        (D.field "text" D.string)


stepDecoder : Decoder Step
stepDecoder =
    D.map4 Step
        (D.field "n" D.int)
        (D.field "text" D.string)
        (D.field "cue" (D.nullable D.string))
        (D.field "timer" (D.nullable D.int))


rescueDecoder : Decoder Rescue
rescueDecoder =
    D.map3 Rescue
        (D.field "symptom" D.string)
        (D.field "recoverable" D.bool)
        (D.field "text" D.string)

